# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 RL-Kernel Contributors

"""Fail-closed statuses for P2 T06. Unsupported/fallback is never PASS."""

from __future__ import annotations

from enum import Enum
from typing import Any


class P2Status(str, Enum):
    PASS = "PASS"
    BYTE_MISMATCH = "BYTE_MISMATCH"
    STATE_BYTES_MISMATCH = "STATE_BYTES_MISMATCH"
    IDENTITY_DRIFT = "IDENTITY_DRIFT"
    INVALID_LAYER_TYPE = "INVALID_LAYER_TYPE"
    INVALID_COMPRESSION_PLAN = "INVALID_COMPRESSION_PLAN"
    INVALID_GLOBAL_POSITION = "INVALID_GLOBAL_POSITION"
    INVALID_PAGE_OR_GENERATION = "INVALID_PAGE_OR_GENERATION"
    EARLY_OR_DUPLICATE_COMMIT = "EARLY_OR_DUPLICATE_COMMIT"
    MAIN_INDEX_IDENTITY_ALIAS = "MAIN_INDEX_IDENTITY_ALIAS"
    INVALID_CANDIDATE_ORDER = "INVALID_CANDIDATE_ORDER"
    MULTIPLE_SOFTMAX_DENOMINATORS = "MULTIPLE_SOFTMAX_DENOMINATORS"
    INVALID_SINK_SEMANTICS = "INVALID_SINK_SEMANTICS"
    INVALID_TOPK_ORDER = "INVALID_TOPK_ORDER"
    AMBIGUOUS_LOGICAL_INDEX = "AMBIGUOUS_LOGICAL_INDEX"
    INVALID_ROPE_VARIANT = "INVALID_ROPE_VARIANT"
    ROUND_POINT_MISMATCH = "ROUND_POINT_MISMATCH"
    FORBIDDEN_SPLIT_REDUCTION = "FORBIDDEN_SPLIT_REDUCTION"
    FORBIDDEN_ATOMIC_REDUCTION = "FORBIDDEN_ATOMIC_REDUCTION"
    MISSING_GLOBAL_VISIBILITY = "MISSING_GLOBAL_VISIBILITY"
    DUPLICATE_LOGICAL_OWNER = "DUPLICATE_LOGICAL_OWNER"
    MISSING_RANK = "MISSING_RANK"
    MISSING_PROVENANCE = "MISSING_PROVENANCE"
    SILENT_FALLBACK = "SILENT_FALLBACK"
    UNSUPPORTED_CAPABILITY = "UNSUPPORTED_CAPABILITY"
    NON_FINITE = "NON_FINITE"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"
    INCOMPLETE_ARTIFACT = "INCOMPLETE_ARTIFACT"
    CORRUPT_ARTIFACT = "CORRUPT_ARTIFACT"
    NATURAL_ROUTE_MISMATCH = "NATURAL_ROUTE_MISMATCH"


class P2FailClosedError(ValueError):
    """Contract violation. ``status`` is the discrete fail-closed code."""

    def __init__(self, status: P2Status | str, message: str, **details: Any) -> None:
        status_enum = status if isinstance(status, P2Status) else P2Status(status)
        super().__init__(f"{status_enum.value}: {message}")
        self.status = status_enum
        self.details = details
